version: '3'
services: 
  app:
    build: .
    container_name: echo_sample_app
    command: realize start
    volumes: 
      - ./:/go/src/app
    ports: 
      - 8080:8080
    depends_on: 
      - db
  db:
    image: mysql:latest
    container_name: echo_sample_mysql
    volumes: 
      - ./mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: rootPwd
      MYSQL_DATABASE: testDb
      MYSQL_USER: testUser
      MYSQL_PASSWORD: pwd
