version: "3"
services:
  app:
    build: .
    container_name: sake_io_api
    command: realize start
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: sake_io_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
