FROM mysql:latest

RUN apt update -y && \
  apt upgrade -y && \
  apt install -y tzdata locales-all && \
  cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8

EXPOSE 3306